image: docker:latest
services:
  - docker:dind

stages:
  - deploy

before_script:
  - apk update && apk add sudo
  - apk add --update py-pip
  - pip install -U setuptools
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install --upgrade pip
  - pip install docker-compose

after_script:
  - flask run migrate

step-deploy-master:
  stage: deploy
  before_script:
    - export DYNAMIC_ENV_VAR=MASTER
  only:
    - master
  script:
    - ls
    - sudo rm -rf db
    - ls
    - chmod u+x deploy.sh
    - ./deploy.sh
  environment: production
  when: manual
