image: docker:latest
services:
  - docker:dind

stages:
  - deploy

step-deploy-master:
  stage: deploy
  before_script:
    - export DYNAMIC_ENV_VAR=MASTER
  only:
    - master
  script:
    - ls
    - cd code
    - ls
    - chmod u+x deploy.sh
    - ./deploy.sh
  environment: production
  when: manual
