"""empty message

Revision ID: 3ae55efc8911
Revises: cdc2dfe18d61
Create Date: 2020-05-16 16:06:33.283726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae55efc8911'
down_revision = 'cdc2dfe18d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'phone2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('phone2', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
