"""empty message

Revision ID: 4fef2f0383b8
Revises: fa22b9dc02b2
Create Date: 2020-05-02 10:30:38.718701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fef2f0383b8'
down_revision = 'fa22b9dc02b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.Text(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('website', sa.String(length=500), nullable=False))
    op.drop_column('Venue', 'seek_talent_text')
    op.drop_column('Venue', 'seek_talent')
    op.drop_column('Venue', 'webpage_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('webpage_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('seek_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('Venue', sa.Column('seek_talent_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
