"""empty message

Revision ID: cdc2dfe18d61
Revises: 39c8add9fcd2
Create Date: 2020-05-16 16:05:55.685903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc2dfe18d61'
down_revision = '39c8add9fcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('phone2', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'phone2')
    # ### end Alembic commands ###
