"""empty message

Revision ID: f9b0f498aa00
Revises: 4dd4105bbef9
Create Date: 2020-05-16 19:23:29.769206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'f9b0f498aa00'
down_revision = '4dd4105bbef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.execute("UPDATE \"Show\" SET start_time = date;")
    op.alter_column('Show', 'start_time', existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, default=datetime.now()))
    op.execute("UPDATE \"Show\" SET date = start_time;")
    op.drop_column('Show', 'start_time')
    op.alter_column('Artist', 'website',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
